### ISSUE TITLE
Verified ve verified olmayan alan pinlerini belirginleştir

### ISSUE THREAD

**Issue by segocago** [segocago/afet-yardim-fe#19]
Verified ve verified olmayan alanlar için farklı bir pin rengi, şekli kullanılabilir.

Aynı zamanda site'larda site status'üne (insan_ihtiyaci_var, materyal_ihtiyacı_var, ihtiyac_yok) vb. göre bir ayrım yapmak gerekebilir.

**Comment by segocago** [comment]
github.com/tolgaozgun yapabilirim dedi bu işi.

**Comment by tolgaozgun** [comment]
1. opsiyon
![image](https://user-images.githubusercontent.com/37017809/217923268-38a136b7-be3e-4190-b35f-1c16d0a22970.png)
![image](https://user-images.githubusercontent.com/37017809/217923280-1f509839-c819-40f7-a303-ad58a8082270.png)

2. opsiyon
![image](https://user-images.githubusercontent.com/37017809/217923402-00484ebb-99e5-43ee-b337-ce4e1ec4ea53.png)
Bu menü hover'da açılabilir. (1. opsiyondaki tarzda bir filtre iconu konur. Üzerine imleçle bakılınca bu resimdeki gibi bir şey gözükür)

**Comment by tolgaozgun** [comment]
#34 ile çözülmüş olmalı
