### ISSUE TITLE
Konut tipinde alan ekleme, filtreleme

### ISSUE THREAD

**Issue by segocago** [segocago/afet-yardim-fe#20]
Ankara yardımlaşma gruplarından böyle bir ihtiyaç olduğu bilgisi geldi. Konut desteği veren yerlerin bir listesini tutuyorlar ama harita yok. Yeni bir site tipi ekleyip frontende de site tipine göre bir filtre eklenebilir. (Sadece konut tiplileri getir, sadece yardım merkezlerini getir vb.)

**Comment by tolgaozgun** [comment]
#34 ile filtre UI'a eklendi. Su anlik bir fonksiyonu yok.
