### ISSUE TITLE
Backend: Pinleri alanların durumuna göre farklı renk/imge ile vb. göndermek

### ISSUE THREAD

**Issue by segocago** [segocago/afet-yardim-fe#26]
Backendi güncelle:

Site {
 
List<SiteStatus>
}

SiteStatus {
MalzemeİhtiyaciVar,İnsanGücüİhtiyaciVar,, GıdaİhtiyaciVar, KoliİhtiyaciVar
}

AddSiteUpdate endpointini güncelle, sitestatus alıp ona göre güncellesin sitestatusu.

**Comment by tolgaozgun** [comment]
Frontend'deki assignlanmis isim bitince devralabilirim, ustunde ugrasmak isteyen varsa o zamana kadar benden alabilir.

**Comment by segocago** [comment]
Berkan Şahin alabilir bu işi. berkan-sahin
