### ISSUE TITLE
Frontend: Markerlari gruplama

### ISSUE THREAD

**Issue by tolgaozgun** [segocago/afet-yardim-fe#30]
Sadece Istanbul'da en azindan 200 marker girecegiz, eger gruplama yapmazsak belirgin performans sorunlari yasayacagiz. 

Onaylarsaniz bu gruplamayi yapabilirim:

![image](https://user-images.githubusercontent.com/37017809/217939742-5e45c879-8809-419f-8f0b-80dc3c834d64.png)

**Comment by selimcanglr** [comment]
#53 bu konuyla alakali. Istanbul verileri girildikten sonra tekrar denenebilir.

**Comment by alkislardeniz** [comment]
@selimcanglr'ın PR'ı geçirdik. İstanbul'u geçirdikten sonra test ettik, işe yaradı.
